/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'status' : TournamentStatus,
  'has3rdPlaceMatch' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Match = IDL.Record({
  'status' : MatchStatus,
  'winnerId' : IDL.Opt(IDL.Principal),
  'score1' : IDL.Int,
  'score2' : IDL.Int,
  'slot' : IDL.Nat,
  'player2Name' : IDL.Text,
  'player1Name' : IDL.Text,
  'round' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'rjzProfileLink' : IDL.Text,
});
export const PublicPlayer = IDL.Record({
  'isGuest' : IDL.Bool,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGuestPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTournament' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getBracketMatches' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournamentPlayers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PublicPlayer)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerTournamentCreator' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat], [], []),
  'kickPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'reorderPlayers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'reportMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, IDL.Int, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startTournament' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'status' : TournamentStatus,
    'has3rdPlaceMatch' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'status' : MatchStatus,
    'winnerId' : IDL.Opt(IDL.Principal),
    'score1' : IDL.Int,
    'score2' : IDL.Int,
    'slot' : IDL.Nat,
    'player2Name' : IDL.Text,
    'player1Name' : IDL.Text,
    'round' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'rjzProfileLink' : IDL.Text,
  });
  const PublicPlayer = IDL.Record({ 'isGuest' : IDL.Bool, 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGuestPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getBracketMatches' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournamentPlayers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PublicPlayer)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerTournamentCreator' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat], [], []),
    'kickPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'reorderPlayers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
    'reportMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, IDL.Int, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startTournament' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
