/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'status' : MatchStatus,
  'winnerId' : [] | [Principal],
  'score1' : bigint,
  'score2' : bigint,
  'slot' : bigint,
  'player2Name' : string,
  'player1Name' : string,
  'round' : bigint,
}
export type MatchStatus = { 'scheduled' : null } |
  { 'completed' : null };
export interface PublicPlayer { 'isGuest' : boolean, 'name' : string }
export interface Tournament {
  'id' : bigint,
  'status' : TournamentStatus,
  'has3rdPlaceMatch' : boolean,
  'name' : string,
  'description' : string,
}
export type TournamentStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface UserProfile { 'name' : string, 'rjzProfileLink' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGuestPlayer' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<[string, string, boolean], bigint>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getBracketMatches' : ActorMethod<[bigint], Array<Match>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournamentPlayers' : ActorMethod<[bigint], Array<PublicPlayer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerTournamentCreator' : ActorMethod<[bigint], boolean>,
  'joinTournament' : ActorMethod<[bigint], undefined>,
  'kickPlayer' : ActorMethod<[bigint, string], undefined>,
  'reorderPlayers' : ActorMethod<[bigint, Array<string>], undefined>,
  'reportMatch' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, [] | [Principal]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTournament' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
