/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'isBanned' : IDL.Bool,
  'tournamentCount' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'status' : TournamentStatus,
  'has3rdPlaceMatch' : IDL.Bool,
  'game' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isCheckInOpen' : IDL.Bool,
  'maxPlayers' : IDL.Opt(IDL.Nat),
});
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Match = IDL.Record({
  'status' : MatchStatus,
  'winnerId' : IDL.Opt(IDL.Principal),
  'score1' : IDL.Int,
  'score2' : IDL.Int,
  'slot' : IDL.Nat,
  'player2Name' : IDL.Text,
  'player1Name' : IDL.Text,
  'round' : IDL.Nat,
});
export const TournamentResult = IDL.Record({
  'placedGold' : IDL.Bool,
  'eliminatedAtStage' : IDL.Text,
  'tournamentName' : IDL.Text,
  'placedSilver' : IDL.Bool,
  'placedBronze' : IDL.Bool,
  'eliminatedByName' : IDL.Text,
  'tournamentId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'rjzProfileLink' : IDL.Text,
});
export const PublicPlayer = IDL.Record({
  'isGuest' : IDL.Bool,
  'name' : IDL.Text,
});
export const PublicUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'userId' : IDL.Text,
  'goldTrophies' : IDL.Nat,
  'name' : IDL.Text,
  'silverTrophies' : IDL.Nat,
  'bronzeTrophies' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addGuestPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'checkIn' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'closeCheckIn' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createTournament' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteTournament' : IDL.Func([IDL.Nat], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTournaments' : IDL.Nat,
          'users' : IDL.Vec(UserInfo),
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getBracketMatches' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
  'getCallerTournamentHistory' : IDL.Func(
      [],
      [IDL.Vec(TournamentResult)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournamentCheckInStatus' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getTournamentPlayers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PublicPlayer)],
      ['query'],
    ),
  'getUserByUserId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTournamentHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TournamentResult)],
      ['query'],
    ),
  'initialize' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerJoinedTournament' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerTournamentCreator' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCheckInOpen' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat], [], []),
  'kickPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'openCheckIn' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'reorderPlayers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'reportMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, IDL.Int, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'startTournament' : IDL.Func([IDL.Nat], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'withdrawFromTournament' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'isBanned' : IDL.Bool,
    'tournamentCount' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'status' : TournamentStatus,
    'has3rdPlaceMatch' : IDL.Bool,
    'game' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isCheckInOpen' : IDL.Bool,
    'maxPlayers' : IDL.Opt(IDL.Nat),
  });
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'status' : MatchStatus,
    'winnerId' : IDL.Opt(IDL.Principal),
    'score1' : IDL.Int,
    'score2' : IDL.Int,
    'slot' : IDL.Nat,
    'player2Name' : IDL.Text,
    'player1Name' : IDL.Text,
    'round' : IDL.Nat,
  });
  const TournamentResult = IDL.Record({
    'placedGold' : IDL.Bool,
    'eliminatedAtStage' : IDL.Text,
    'tournamentName' : IDL.Text,
    'placedSilver' : IDL.Bool,
    'placedBronze' : IDL.Bool,
    'eliminatedByName' : IDL.Text,
    'tournamentId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'rjzProfileLink' : IDL.Text,
  });
  const PublicPlayer = IDL.Record({ 'isGuest' : IDL.Bool, 'name' : IDL.Text });
  const PublicUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'userId' : IDL.Text,
    'goldTrophies' : IDL.Nat,
    'name' : IDL.Text,
    'silverTrophies' : IDL.Nat,
    'bronzeTrophies' : IDL.Nat,
  });
  
  return IDL.Service({
    'addGuestPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'checkIn' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'closeCheckIn' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteTournament' : IDL.Func([IDL.Nat], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTournaments' : IDL.Nat,
            'users' : IDL.Vec(UserInfo),
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getBracketMatches' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
    'getCallerTournamentHistory' : IDL.Func(
        [],
        [IDL.Vec(TournamentResult)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournamentCheckInStatus' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getTournamentPlayers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PublicPlayer)],
        ['query'],
      ),
    'getUserByUserId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTournamentHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TournamentResult)],
        ['query'],
      ),
    'initialize' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerJoinedTournament' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerTournamentCreator' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCheckInOpen' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat], [], []),
    'kickPlayer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'openCheckIn' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'reorderPlayers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
    'reportMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, IDL.Int, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'startTournament' : IDL.Func([IDL.Nat], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'withdrawFromTournament' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };