/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'status' : MatchStatus,
  'winnerId' : [] | [Principal],
  'score1' : bigint,
  'score2' : bigint,
  'slot' : bigint,
  'player2Name' : string,
  'player1Name' : string,
  'round' : bigint,
}
export type MatchStatus = { 'scheduled' : null } |
  { 'completed' : null };
export interface PublicPlayer { 'isGuest' : boolean, 'name' : string }
export interface PublicUserProfile {
  'bio' : string,
  'userId' : string,
  'goldTrophies' : bigint,
  'name' : string,
  'silverTrophies' : bigint,
  'bronzeTrophies' : bigint,
}
export interface Tournament {
  'id' : bigint,
  'status' : TournamentStatus,
  'has3rdPlaceMatch' : boolean,
  'game' : string,
  'name' : string,
  'description' : string,
  'isCheckInOpen' : boolean,
  'maxPlayers' : [] | [bigint],
}
export interface TournamentResult {
  'placedGold' : boolean,
  'eliminatedAtStage' : string,
  'tournamentName' : string,
  'placedSilver' : boolean,
  'placedBronze' : boolean,
  'eliminatedByName' : string,
  'tournamentId' : bigint,
}
export type TournamentStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface UserInfo {
  'principal' : Principal,
  'name' : string,
  'isBanned' : boolean,
  'tournamentCount' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'userId' : string,
  'name' : string,
  'rjzProfileLink' : string,
}
export interface _SERVICE {
  'addGuestPlayer' : ActorMethod<[bigint, string], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Player checks in to a tournament. Must be a registered player in this tournament.
   */
  'checkIn' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  /**
   * / Close check-in for a tournament. Only tournament creator or admin.
   */
  'closeCheckIn' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'createTournament' : ActorMethod<[string, string, boolean, bigint], bigint>,
  'deleteTournament' : ActorMethod<[bigint], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalTournaments' : bigint,
      'users' : Array<UserInfo>,
      'totalUsers' : bigint,
    }
  >,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getBracketMatches' : ActorMethod<[bigint], Array<Match>>,
  /**
   * / Get tournament history for the caller. Most recent first.
   */
  'getCallerTournamentHistory' : ActorMethod<[], Array<TournamentResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  /**
   * / Get check-in status for all players in a tournament. Public query.
   * / Returns [(playerDisplayName, hasCheckedIn)] for registered players.
   */
  'getTournamentCheckInStatus' : ActorMethod<
    [bigint],
    { 'ok' : Array<[string, boolean]> } |
      { 'err' : string }
  >,
  'getTournamentPlayers' : ActorMethod<[bigint], Array<PublicPlayer>>,
  /**
   * / Look up a public profile by unique userId. No auth required.
   */
  'getUserByUserId' : ActorMethod<[string], [] | [PublicUserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get tournament history for any user by principal. No auth required.
   */
  'getUserTournamentHistory' : ActorMethod<
    [Principal],
    Array<TournamentResult>
  >,
  'initialize' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerJoinedTournament' : ActorMethod<[bigint], boolean>,
  'isCallerTournamentCreator' : ActorMethod<[bigint], boolean>,
  /**
   * / Check whether check-in is open for a tournament. Public query.
   */
  'isCheckInOpen' : ActorMethod<[bigint], boolean>,
  'joinTournament' : ActorMethod<[bigint], undefined>,
  'kickPlayer' : ActorMethod<[bigint, string], undefined>,
  /**
   * / Open check-in for a tournament. Only tournament creator or admin.
   * / Initializes all current registered players as not checked in.
   */
  'openCheckIn' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'reorderPlayers' : ActorMethod<[bigint, Array<string>], undefined>,
  'reportMatch' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, [] | [Principal]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'startTournament' : ActorMethod<[bigint], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'withdrawFromTournament' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];