/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PublicPlayer {
    isGuest: boolean;
    name: string;
}
export interface PublicUserProfile {
    bio: string;
    userId: string;
    goldTrophies: bigint;
    name: string;
    silverTrophies: bigint;
    bronzeTrophies: bigint;
}
export interface Tournament {
    id: bigint;
    status: TournamentStatus;
    has3rdPlaceMatch: boolean;
    game: string;
    name: string;
    description: string;
    isCheckInOpen: boolean;
    maxPlayers?: bigint;
}
export interface TournamentResult {
    placedGold: boolean;
    eliminatedAtStage: string;
    tournamentName: string;
    placedSilver: boolean;
    placedBronze: boolean;
    eliminatedByName: string;
    tournamentId: bigint;
}
export interface Match {
    status: MatchStatus;
    winnerId?: Principal;
    score1: bigint;
    score2: bigint;
    slot: bigint;
    player2Name: string;
    player1Name: string;
    round: bigint;
}
export interface UserInfo {
    principal: Principal;
    name: string;
    isBanned: boolean;
    tournamentCount: bigint;
}
export interface UserProfile {
    bio: string;
    userId: string;
    name: string;
    rjzProfileLink: string;
}
export enum MatchStatus {
    scheduled = "scheduled",
    completed = "completed"
}
export enum TournamentStatus {
    active = "active",
    pending = "pending",
    completed = "completed"
}
export interface backendInterface {
    addGuestPlayer(tournamentId: bigint, name: string): Promise<void>;
    banUser(user: Principal): Promise<void>;
    /**
     * / Player checks in to a tournament. Must be a registered player in this tournament.
     */
    checkIn(tournamentId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Close check-in for a tournament. Only tournament creator or admin.
     */
    closeCheckIn(tournamentId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createTournament(name: string, description: string, has3rdPlaceMatch: boolean, maxPlayers: bigint): Promise<bigint>;
    deleteTournament(tournamentId: bigint): Promise<void>;
    getAdminStats(): Promise<{
        totalTournaments: bigint;
        users: Array<UserInfo>;
        totalUsers: bigint;
    }>;
    getAllTournaments(): Promise<Array<Tournament>>;
    getBracketMatches(tournamentId: bigint): Promise<Array<Match>>;
    /**
     * / Get tournament history for the caller. Most recent first.
     */
    getCallerTournamentHistory(): Promise<Array<TournamentResult>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getTournament(tournamentId: bigint): Promise<Tournament | null>;
    /**
     * / Get check-in status for all players in a tournament. Public query.
     * / Returns [(playerDisplayName, hasCheckedIn)] for registered players.
     */
    getTournamentCheckInStatus(tournamentId: bigint): Promise<{
        __kind__: "ok";
        ok: Array<[string, boolean]>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTournamentPlayers(tournamentId: bigint): Promise<Array<PublicPlayer>>;
    /**
     * / Look up a public profile by unique userId. No auth required.
     */
    getUserByUserId(userId: string): Promise<PublicUserProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / Get tournament history for any user by principal. No auth required.
     */
    getUserTournamentHistory(user: Principal): Promise<Array<TournamentResult>>;
    initialize(_token: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerJoinedTournament(tournamentId: bigint): Promise<boolean>;
    isCallerTournamentCreator(tournamentId: bigint): Promise<boolean>;
    /**
     * / Check whether check-in is open for a tournament. Public query.
     */
    isCheckInOpen(tournamentId: bigint): Promise<boolean>;
    joinTournament(tournamentId: bigint): Promise<void>;
    kickPlayer(tournamentId: bigint, playerName: string): Promise<void>;
    /**
     * / Open check-in for a tournament. Only tournament creator or admin.
     * / Initializes all current registered players as not checked in.
     */
    openCheckIn(tournamentId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    reorderPlayers(tournamentId: bigint, orderedNames: Array<string>): Promise<void>;
    reportMatch(tournamentId: bigint, round: bigint, slot: bigint, score1: bigint, score2: bigint, winnerId: Principal | null): Promise<void>;
    saveCallerUserProfile(name: string, bio: string): Promise<void>;
    startTournament(tournamentId: bigint): Promise<void>;
    unbanUser(user: Principal): Promise<void>;
    withdrawFromTournament(tournamentId: bigint): Promise<void>;
}
import type { Match as _Match, MatchStatus as _MatchStatus, PublicUserProfile as _PublicUserProfile, Tournament as _Tournament, TournamentStatus as _TournamentStatus, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGuestPlayer(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGuestPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGuestPlayer(arg0, arg1);
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async checkIn(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async closeCheckIn(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.closeCheckIn(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeCheckIn(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTournament(arg0: string, arg1: string, arg2: boolean, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0);
            return result;
        }
    }
    async getAdminStats(): Promise<{
        totalTournaments: bigint;
        users: Array<UserInfo>;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBracketMatches(arg0: bigint): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBracketMatches(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBracketMatches(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerTournamentHistory(): Promise<Array<TournamentResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTournamentHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTournamentHistory();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournament(arg0: bigint): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentCheckInStatus(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Array<[string, boolean]>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentCheckInStatus(arg0);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentCheckInStatus(arg0);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentPlayers(arg0: bigint): Promise<Array<PublicPlayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentPlayers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentPlayers(arg0);
            return result;
        }
    }
    async getUserByUserId(arg0: string): Promise<PublicUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUserId(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUserId(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTournamentHistory(arg0: Principal): Promise<Array<TournamentResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTournamentHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTournamentHistory(arg0);
            return result;
        }
    }
    async initialize(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerJoinedTournament(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerJoinedTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerJoinedTournament(arg0);
            return result;
        }
    }
    async isCallerTournamentCreator(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerTournamentCreator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerTournamentCreator(arg0);
            return result;
        }
    }
    async isCheckInOpen(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCheckInOpen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCheckInOpen(arg0);
            return result;
        }
    }
    async joinTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournament(arg0);
            return result;
        }
    }
    async kickPlayer(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.kickPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kickPlayer(arg0, arg1);
            return result;
        }
    }
    async openCheckIn(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.openCheckIn(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openCheckIn(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderPlayers(arg0: bigint, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderPlayers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderPlayers(arg0, arg1);
            return result;
        }
    }
    async reportMatch(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportMatch(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportMatch(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async startTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTournament(arg0);
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async withdrawFromTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawFromTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawFromTournament(arg0);
            return result;
        }
    }
}
function from_candid_MatchStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : from_candid_Tournament_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUserProfile]): PublicUserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _MatchStatus;
    winnerId: [] | [Principal];
    score1: bigint;
    score2: bigint;
    slot: bigint;
    player2Name: string;
    player1Name: string;
    round: bigint;
}): {
    status: MatchStatus;
    winnerId?: Principal;
    score1: bigint;
    score2: bigint;
    slot: bigint;
    player2Name: string;
    player1Name: string;
    round: bigint;
} {
    return {
        status: from_candid_MatchStatus_n11(_uploadFile, _downloadFile, value.status),
        winnerId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.winnerId)),
        score1: value.score1,
        score2: value.score2,
        slot: value.slot,
        player2Name: value.player2Name,
        player1Name: value.player1Name,
        round: value.round
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TournamentStatus;
    has3rdPlaceMatch: boolean;
    game: string;
    name: string;
    description: string;
    isCheckInOpen: boolean;
    maxPlayers: [] | [bigint];
}): {
    id: bigint;
    status: TournamentStatus;
    has3rdPlaceMatch: boolean;
    game: string;
    name: string;
    description: string;
    isCheckInOpen: boolean;
    maxPlayers?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TournamentStatus_n5(_uploadFile, _downloadFile, value.status),
        has3rdPlaceMatch: value.has3rdPlaceMatch,
        game: value.game,
        name: value.name,
        description: value.description,
        isCheckInOpen: value.isCheckInOpen,
        maxPlayers: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.maxPlayers))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    completed: null;
}): MatchStatus {
    return "scheduled" in value ? MatchStatus.scheduled : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<[string, boolean]>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<[string, boolean]>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    completed: null;
}): TournamentStatus {
    return "active" in value ? TournamentStatus.active : "pending" in value ? TournamentStatus.pending : "completed" in value ? TournamentStatus.completed : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n9(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
